version: 2

models:
  - name: staging_patient_referrals
    columns:
    - name: reference_id
      description: Unique referral code issued by the chatbot to the field staff member
    - name: referral_date
      description: Date the referral was raised
    - name: phc
      description: PHC / village catchment area the field staff member was operating in
    - name: referrer_department
      description: Team/department of the field staff member who raised the referral (e.g. MMU, MHD)
    - name: referrer_name
      description: Name of the field staff member who raised the referral
    - name: patient_name
      description: Name of the patient being referred
    - name: patient_age
      description: Age of the patient as entered in source
    - name: patient_gender
      description: Gender of the patient as entered in source
    - name: opd_departments
      description: Hospital OPD department the patient was referred to
    - name: referral_status
      description: Status of the referral (e.g. pending, completed, cancelled)
    - name: referrer_id
      description: Unique identifier of the field staff member who raised the referral
    - name: patient_taluka
      description: Taluka of the patient as entered in source
    - name: service_facility_type
      description: Type of service facility the patient was referred to (e.g. SEARCH, Government Hospital, Other)
    - name: Other_facility_name
      description: Name of the other facility if service_facility_type is 'Other'
    - name: referred_to_department
      description: Department the patient was referred to at the service facility SEARCH only.
    - name: followup_status
      description: Status of the follow-up for the referral (e.g. visited, pending, follow-up in progress)
    - name: opd_category
      description: Category of the OPD department the patient was referred to (e.g. Regular OPD, Specialty OPD, Catract Surgery)
    - name: patient_village
      description: Village of the patient as entered in source
    - name: referrer_by_who
      description: Name of the person who referred the patient (e.g. ASHA, MMU Docter, MHD counsellor)        
    - name: visit_date
      description: Date the patient visited the referred facility
    - name: followup_visit_count
      description: Number of follow-up visits the has done by search employee for the patient after the initial referral
    - name: referred_by_doctor
      description: Name of the doctor who referred the patient to the service facility.
    - name: facility_visited
      description: Name of the facility visited by the patient after referral.  
    - name: referral_recorded_date
      description: Date when the referral record was created in the chatbot system

  - name: staging_supervisor_visit
    columns:
    - name: reference_id  
      description: Unique referral code issued by the chatbot to the field staff member 
    - name: visit_date
      description: Date of the follow-up visit made by the field staff member to the patient after referral
    - name: supervisor_name
      description: Name of the field staff member (Supervisor) who made the follow-up visit
    - name: facility_visited
      description: Name of the facility visited by the patient during the follow-up visit
    - name: patient_health_status
      description: Health status of the patient as observed during the follow-up visit
    - name: non_visit_reason
      description: Reason provided if the patient was not visited during the follow-up visit
             