{{ config(materialized='table') }}

-- This model creates a wide format with actual question text as column names
-- Uses the question lookup to create readable column headers

with base_data as (
    select
        participant_id,
        participant_name,
        workshop_name,
        batch,
        case 
            when batch::numeric = floor(batch::numeric) then 0.1
            when round(batch::numeric - floor(batch::numeric), 1) = 0.2 then 0.2
            when round(batch::numeric - floor(batch::numeric), 1) = 0.3 then 0.3
        end as workshop_level,
        workshop_phase,

        -- Career questions (8)
        max(case when question_code = 'carrer_1' then coalesce(cast(response_int as text), response_text) end) as "Goverment Service",
        max(case when question_code = 'carrer_2' then coalesce(cast(response_int as text), response_text) end) as "Job in Private Industry",
        max(case when question_code = 'carrer_3' then coalesce(cast(response_int as text), response_text) end) as "Own Buisness",
        max(case when question_code = 'carrer_4' then coalesce(cast(response_int as text), response_text) end) as "Social Entrepreneurship/Own NGO",
        max(case when question_code = 'carrer_5' then coalesce(cast(response_int as text), response_text) end) as "Working in NGO",
        max(case when question_code = 'carrer_6' then coalesce(cast(response_int as text), response_text) end) as "Academic (College/University)",
        max(case when question_code = 'carrer_7' then coalesce(cast(response_int as text), response_text) end) as "Confused / Not Decided",
        max(case when question_code = 'carrer_8' then coalesce(cast(response_int as text), response_text) end) as "Other",

        -- Criteria questions (9)
        max(case when question_code = 'criteria_1' then coalesce(cast(response_int as text), response_text) end) as "Geographical Location",
        max(case when question_code = 'criteria_2' then coalesce(cast(response_int as text), response_text) end) as "Financial Security",
        max(case when question_code = 'criteria_3' then coalesce(cast(response_int as text), response_text) end) as "Work Satisfaction",
        max(case when question_code = 'criteria_4' then coalesce(cast(response_int as text), response_text) end) as "Cause of My work",
        max(case when question_code = 'criteria_5' then coalesce(cast(response_int as text), response_text) end) as "Carrer progress/growth",
        max(case when question_code = 'criteria_6' then coalesce(cast(response_int as text), response_text) end) as "Work Life Balance",
        max(case when question_code = 'criteria_7' then coalesce(cast(response_int as text), response_text) end) as "Financial Prosperity",
        max(case when question_code = 'criteria_8' then coalesce(cast(response_int as text), response_text) end) as "Fame / Recognition",
        max(case when question_code = 'criteria_9' then coalesce(cast(response_int as text), response_text) end) as "Job Security",

        -- Insecurities questions (10)
        max(case when question_code = 'insecurities_1' then coalesce(cast(response_int as text), response_text) end) as "Social Acceptability",
        max(case when question_code = 'insecurities_2' then coalesce(cast(response_int as text), response_text) end) as "Monetary Compensation",
        max(case when question_code = 'insecurities_3' then coalesce(cast(response_int as text), response_text) end) as "Response of Parents",
        max(case when question_code = 'insecurities_4' then coalesce(cast(response_int as text), response_text) end) as "Difficulty in finding the sutaible life partner",
        max(case when question_code = 'insecurities_5' then coalesce(cast(response_int as text), response_text) end) as "Underutilisation of my talent and skills",
        max(case when question_code = 'insecurities_6' then coalesce(cast(response_int as text), response_text) end) as "Less comfertable lifestyle as compared to my usual peers",
        max(case when question_code = 'insecurities_7' then coalesce(cast(response_int as text), response_text) end) as "Not being Able to create any visible impact",
        max(case when question_code = 'insecurities_8' then coalesce(cast(response_int as text), response_text) end) as "Feeling professionaly leftout",
        max(case when question_code = 'insecurities_9' then coalesce(cast(response_int as text), response_text) end) as "Lack of satisfaction at the end of life",
        max(case when question_code = 'insecurities_10' then coalesce(cast(response_int as text), response_text) end) as "Will my life be less Comfortable than it currently is",

        -- Social contribution
        max(case when question_code = 'social_contribution' then coalesce(cast(response_int as text), response_text) end) as "During my productive lifetime I plan to engage in social contribution",

        -- Self-assessment questions (q1-q64) — with alias merges
        max(case when question_code = 'question_1' then coalesce(cast(response_int as text), response_text) end) as "I feel happy about myself. I like who I am.",
        max(case when question_code = 'question_2' then coalesce(cast(response_int as text), response_text) end) as "I have a good understanding about various social issues around me and their severity",
        max(case when question_code = 'question_3' then coalesce(cast(response_int as text), response_text) end) as "I believe that there is a purpose to my life",
        max(case when question_code = 'question_4' then coalesce(cast(response_int as text), response_text) end) as "I clearly know which sector I will be working in the long term",
        max(case when question_code = 'question_5' then coalesce(cast(response_int as text), response_text) end) as "I know what my values are",
        max(case when question_code = 'question_6' then coalesce(cast(response_int as text), response_text) end) as "I have mentor / facilitators I can talk to regarding myself, my confusions, my future plans",
        max(case when question_code in ('question_7', 'question_88') then coalesce(cast(response_int as text), response_text) end) as "I can take a specific stand about various social issues around me and in my vicinity",
        max(case when question_code = 'question_8' then coalesce(cast(response_int as text), response_text) end) as "I have the courage of going against the flow of conventional career options",
        max(case when question_code = 'question_9' then coalesce(cast(response_int as text), response_text) end) as "I am aware of various ways / approaches of solving social problems",
        max(case when question_code in ('question_10', 'question_139') then coalesce(cast(response_int as text), response_text) end) as "I do serious readinng to build my moral and political philosophy",
        max(case when question_code = 'question_11' then coalesce(cast(response_int as text), response_text) end) as "I usually act on my intentions to work towards social issues",
        max(case when question_code = 'question_12' then coalesce(cast(response_int as text), response_text) end) as "I know what is my 'Swa-dharma'",
        max(case when question_code = 'question_13' then coalesce(cast(response_int as text), response_text) end) as "I feel secure about my financial future",
        max(case when question_code in ('question_14', 'question_140') then coalesce(cast(response_int as text), response_text) end) as "I am a person who believes that it's my responsibility to take action for social change",
        max(case when question_code = 'question_15' then coalesce(cast(response_int as text), response_text) end) as "I have many likeminded friends who also believe in taking action for social change",
        max(case when question_code = 'question_16' then coalesce(cast(response_int as text), response_text) end) as "I have found a purpose for my life",
        max(case when question_code in ('question_17', 'question_94') then coalesce(cast(response_int as text), response_text) end) as "I know quite clearly what are my personal drives, motivations for social action",
        max(case when question_code = 'question_18' then coalesce(cast(response_int as text), response_text) end) as "I find connection between my personal career and social work & expect to contribute accordingly",
        max(case when question_code = 'question_19' then coalesce(cast(response_int as text), response_text) end) as "I am actively involved in the process of meaning-making for my life",
        max(case when question_code = 'question_20' then coalesce(cast(response_int as text), response_text) end) as "I have a larger social dream that I can relate to",
        max(case when question_code = 'question_21' then coalesce(cast(response_int as text), response_text) end) as "I feel that I belong to a diverse and caring community",
        max(case when question_code in ('question_22', 'question_122', 'question_128') then coalesce(cast(response_int as text), response_text) end) as "I understand the difference between social work activities and the social problem solving approach",
        max(case when question_code in ('question_23', 'question_65') then coalesce(cast(response_int as text), response_text) end) as "I know that even if I fail, there are people out there to support me",
        max(case when question_code in ('question_24', 'question_66') then coalesce(cast(response_int as text), response_text) end) as "I find social problem solving intellectually exciting",
        max(case when question_code in ('question_25', 'question_67', 'question_131') then coalesce(cast(response_int as text), response_text) end) as "I can imagine myself as an impactful social change-maker",
        max(case when question_code in ('question_26', 'question_68') then coalesce(cast(response_int as text), response_text) end) as "I believe engaging with society is crucial for me to live a meaningful life",
        max(case when question_code in ('question_27', 'question_69') then coalesce(cast(response_int as text), response_text) end) as "There are inspiring role models in the social field that I can look up to",
        max(case when question_code in ('question_28', 'question_70') then coalesce(cast(response_int as text), response_text) end) as "I feel confident about my potential to bring about positive social change",
        max(case when question_code in ('question_29', 'question_71') then coalesce(cast(response_int as text), response_text) end) as "I understand the difference between happiness and meaning",
        max(case when question_code in ('question_30', 'question_72', 'question_133') then coalesce(cast(response_int as text), response_text) end) as "I feel I am an emotionally mature adult",
        max(case when question_code in ('question_31', 'question_73') then coalesce(cast(response_int as text), response_text) end) as "I think I am quite privileged in being who I am today",
        max(case when question_code in ('question_32', 'question_74') then coalesce(cast(response_int as text), response_text) end) as "I clearly know the differences between my needs and my wants",
        max(case when question_code = 'question_33' then coalesce(cast(response_int as text), response_text) end) as "15 years from now I see myself as an example that will encourage other youth to engage in social action",
        max(case when question_code in ('question_34', 'question_75') then coalesce(cast(response_int as text), response_text) end) as "I have a guiding life philosophy or moral framework to steer me through life decisions",
        max(case when question_code in ('question_35', 'question_76') then coalesce(cast(response_int as text), response_text) end) as "I am confident in experimenting with my life",
        max(case when question_code in ('question_36', 'question_77') then coalesce(cast(response_int as text), response_text) end) as "I get plenty of opportunities to reflect on what is it that I really want to do",
        max(case when question_code in ('question_37', 'question_78', 'question_104') then coalesce(cast(response_int as text), response_text) end) as "All things considered, I am satisfied with my life as a whole these days",
        max(case when question_code in ('question_38', 'question_79') then coalesce(cast(response_int as text), response_text) end) as "I think there are definite rights and wrongs, morals are not relative",
        max(case when question_code = 'question_39' then coalesce(cast(response_int as text), response_text) end) as "I am comfortable in expressing my feelings",
        max(case when question_code in ('question_40', 'question_80') then coalesce(cast(response_int as text), response_text) end) as "I believe that engaging in a path of pro-social purpose will have a positive effect on my well-being",
        max(case when question_code = 'question_41' then coalesce(cast(response_int as text), response_text) end) as "I know what it means to be a flourishing youth",
        max(case when question_code in ('question_42', 'question_91') then coalesce(cast(response_int as text), response_text) end) as "I understand the scientific definition of 'purpose'",
        max(case when question_code = 'question_43' then coalesce(cast(response_int as text), response_text) end) as "Multiple life possibilities of my 20s fill me with excitement",
        max(case when question_code = 'question_44' then coalesce(cast(response_int as text), response_text) end) as "Finding my purpose in life is the most urgent priority for me",
        max(case when question_code = 'question_45' then coalesce(cast(response_int as text), response_text) end) as "I understand the difference between leading a 'happy life' and a 'meaningful life'",
        max(case when question_code = 'question_46' then coalesce(cast(response_int as text), response_text) end) as "I understand the difference between goal and purpose",
        max(case when question_code = 'question_47' then coalesce(cast(response_int as text), response_text) end) as "The more money one earns, the more happy they are",
        max(case when question_code = 'question_48' then coalesce(cast(response_int as text), response_text) end) as "I understand how to apply 'categorical moral framework' while making important life decisions",
        max(case when question_code = 'question_49' then coalesce(cast(response_int as text), response_text) end) as "The process of finding / working on my purpose fills me with excitement",
        max(case when question_code = 'question_50' then coalesce(cast(response_int as text), response_text) end) as "The question of 'how much money would I earn in life' does not bother me",
        max(case when question_code = 'question_51' then coalesce(cast(response_int as text), response_text) end) as "From those to whom much is given, much is expected",
        max(case when question_code = 'question_52' then coalesce(cast(response_int as text), response_text) end) as "I value the 'freedom to work on my chosen challenge' more than other opportunities with even higher financial gains",
        max(case when question_code = 'question_53' then coalesce(cast(response_int as text), response_text) end) as "I understand the importance of purpose and the various advantages associated with it",
        max(case when question_code = 'question_54' then coalesce(cast(response_int as text), response_text) end) as "Leading a life of 'social contribution' is one of my deepest quests",
        max(case when question_code in ('question_55', 'question_87') then coalesce(cast(response_int as text), response_text) end) as "I know how an 'impactful social organisation' functions",
        max(case when question_code = 'question_56' then coalesce(cast(response_int as text), response_text) end) as "There are many 'social change makers' that I know of and feel inspired by",
        max(case when question_code in ('question_57', 'question_102', 'question_126', 'question_130') then coalesce(cast(response_int as text), response_text) end) as "I can visualise possible ways in which I can contribute in the social sector",
        max(case when question_code = 'question_58' then coalesce(cast(response_int as text), response_text) end) as "I know the difference between my 'minimum threshold income for financial security' and my 'aspirational income'",
        max(case when question_code = 'question_59' then coalesce(cast(response_int as text), response_text) end) as "I think it's safe to drink alcohol if consumed within limits",
        max(case when question_code in ('question_60', 'question_101') then coalesce(cast(response_int as text), response_text) end) as "I have identified specific books to read in the coming year",
        max(case when question_code in ('question_61', 'question_103') then coalesce(cast(response_int as text), response_text) end) as "I plan to proactively engage in actions to reduce my 'carbon footprint'",
        max(case when question_code = 'question_62' then coalesce(cast(response_int as text), response_text) end) as "I have identified specific actions to work upon in the next 6 months regarding my own flourishing",
        max(case when question_code = 'question_63' then coalesce(cast(response_int as text), response_text) end) as "I know some specific actions to do in the next 6 months as part of my social contribution",
        max(case when question_code = 'question_64' then coalesce(cast(response_int as text), response_text) end) as "I have identified few specific actions to pursue my purpose journey",

        -- Self-assessment questions (q81-q109)
        max(case when question_code = 'question_81' then coalesce(cast(response_int as text), response_text) end) as "I know how to become a 'flourishing youth'",
        max(case when question_code = 'question_82' then coalesce(cast(response_int as text), response_text) end) as "I can visualize at least 5 different career paths for myself",
        max(case when question_code = 'question_83' then coalesce(cast(response_int as text), response_text) end) as "I productively spend my day in meaningful pursuits",
        max(case when question_code = 'question_84' then coalesce(cast(response_int as text), response_text) end) as "I am committed to bringing about social change",
        max(case when question_code in ('question_85', 'question_117', 'question_141') then coalesce(cast(response_int as text), response_text) end) as "I have a mentor(s) with whom I can discuss important life matters",
        max(case when question_code in ('question_86', 'question_142') then coalesce(cast(response_int as text), response_text) end) as "I have a 'guiding philosophy' to steer me through life",
        max(case when question_code = 'question_89' then coalesce(cast(response_int as text), response_text) end) as "I know how to understand and analyse a social change intervention",
        max(case when question_code = 'question_90' then coalesce(cast(response_int as text), response_text) end) as "I feel anxious about fulfilling financial aspirations / ambitions of my life",
        max(case when question_code = 'question_92' then coalesce(cast(response_int as text), response_text) end) as "I know the building blocks of effective social problem-solving",
        max(case when question_code in ('question_93', 'question_119') then coalesce(cast(response_int as text), response_text) end) as "I am clear about the process of finding and pursuing my purpose in life",
        max(case when question_code = 'question_95' then coalesce(cast(response_int as text), response_text) end) as "I can stay firm on my values even if they are against conventional norms",
        max(case when question_code = 'question_96' then coalesce(cast(response_int as text), response_text) end) as "I understand different approaches / methods of bringing about social change",
        max(case when question_code = 'question_97' then coalesce(cast(response_int as text), response_text) end) as "I understand the importance and urgency of identifying my purpose in life",
        max(case when question_code = 'question_98' then coalesce(cast(response_int as text), response_text) end) as "I have a 'set of values' that help me in making important life decisions",
        max(case when question_code = 'question_99' then coalesce(cast(response_int as text), response_text) end) as "I have a fair idea about what to do with my life",
        max(case when question_code = 'question_100' then coalesce(cast(response_int as text), response_text) end) as "I have carefully identified a set of moral resolutions to follow in my daily living",
        max(case when question_code = 'question_105' then coalesce(cast(response_int as text), response_text) end) as "I have identified specific actions to do in the next 1 year to pursue my purpose journey",
        max(case when question_code = 'question_106' then coalesce(cast(response_int as text), response_text) end) as "I clearly know which sector I will be working in for most of my professional life",
        max(case when question_code = 'question_107' then coalesce(cast(response_int as text), response_text) end) as "I have planned specific actions to do in the next 1 year as part of my social change-making journey",
        max(case when question_code = 'question_108' then coalesce(cast(response_int as text), response_text) end) as "I am empowered to enact my responsibilities as an 'Active Citizen' while dealing with the state",
        max(case when question_code = 'question_109' then coalesce(cast(response_int as text), response_text) end) as "I have a clear sense of purpose in my life",

        -- Self-assessment questions (q110-q126)
        max(case when question_code = 'question_110' then coalesce(cast(response_int as text), response_text) end) as "I can think of at least 5 different life possibilities based on the decisions I make in my youth",
        max(case when question_code = 'question_111' then coalesce(cast(response_int as text), response_text) end) as "There is more to life than continuous consumption of exotic experiences and materialistic pleasures",
        max(case when question_code = 'question_112' then coalesce(cast(response_int as text), response_text) end) as "I feel anxious about how I will find / pursue my purpose in life",
        max(case when question_code = 'question_113' then coalesce(cast(response_int as text), response_text) end) as "I am solely responsible for the success I have achieved in my life",
        max(case when question_code = 'question_114' then coalesce(cast(response_int as text), response_text) end) as "Large number youth pursuing a career in the social sector is an important need of our today's society",
        max(case when question_code = 'question_115' then coalesce(cast(response_int as text), response_text) end) as "I know my values / morals and I can take a firm stand about them even in the face of opposition",
        max(case when question_code = 'question_116' then coalesce(cast(response_int as text), response_text) end) as "I have decided a few moral lifestyle resolutions that I follow",
        max(case when question_code = 'question_118' then coalesce(cast(response_int as text), response_text) end) as "I know how a life of meaningfulness looks different from a life of pleasure-seeking, & I have the clarity to choose among them",
        max(case when question_code = 'question_120' then coalesce(cast(response_int as text), response_text) end) as "I understand the need, importance and unique roles of the social sector in society",
        max(case when question_code = 'question_121' then coalesce(cast(response_int as text), response_text) end) as "I exhibit the courage to live authentically with my values and beliefs even if they are against conventional norms",
        max(case when question_code = 'question_123' then coalesce(cast(response_int as text), response_text) end) as "I have given a careful thought to what I want to do in my life",
        max(case when question_code = 'question_124' then coalesce(cast(response_int as text), response_text) end) as "My choice of what I want to do in my life is not majorly influenced by the norms followed by my peers, seniors, society",
        max(case when question_code = 'question_125' then coalesce(cast(response_int as text), response_text) end) as "I know the difference between my 'financial needs' and my 'aspirational income'",

        -- NEW: Batch .3 questions (q127+) — genuinely new questions
        max(case when question_code = 'question_127' then coalesce(cast(response_int as text), response_text) end) as "Although most people wish to join pvt. or govt. sector, I can visualize myself pursuing a career in the social sector",
        max(case when question_code = 'question_129' then coalesce(cast(response_int as text), response_text) end) as "The elevation I feel when I see or read about other people devoting their lives for a social mission, strongly motivates me to act for social change",
        max(case when question_code = 'question_132' then coalesce(cast(response_int as text), response_text) end) as "My self actualisation is intemently linked with the others in the society",
        max(case when question_code = 'question_134' then coalesce(cast(response_int as text), response_text) end) as "I don't have a lear understanding between my needs and my wants",
        max(case when question_code = 'question_135' then coalesce(cast(response_int as text), response_text) end) as "My undrstanding of the broader social economic issues is very poor",
        max(case when question_code = 'question_136' then coalesce(cast(response_int as text), response_text) end) as "I don't get opportunity to reflect on what it is that I really want to do",
        max(case when question_code = 'question_137' then coalesce(cast(response_int as text), response_text) end) as "I think morals are relative, there are no definite rights and wrongs for everybody",
        max(case when question_code = 'question_138' then coalesce(cast(response_int as text), response_text) end) as "I doubt that engaging in a path of social purpose might affect my well-being adversely",
        max(case when question_code = 'question_143' then coalesce(cast(response_int as text), response_text) end) as "Parental agreement is a mandatory requirement for me to take any decision on my life & career",
        max(case when question_code = 'question_144' then coalesce(cast(response_int as text), response_text) end) as "I will prefer a path that ensures my safety and security needs of life",
        max(case when question_code = 'question_145' then coalesce(cast(response_int as text), response_text) end) as "I do experiment / change in my lifestyle to make it environment friendly",
        max(case when question_code = 'question_146' then coalesce(cast(response_int as text), response_text) end) as "I Think It is my responsibility to give back to society",
        max(case when question_code = 'question_147' then coalesce(cast(response_int as text), response_text) end) as "My efforts have contributed more to who I am today than when, where and to whom I was born",
        max(case when question_code = 'question_148' then coalesce(cast(response_int as text), response_text) end) as "Since you live only once, I believe that one should have as many materialistic pleasures and experiences as possible",
        max(case when question_code = 'question_149' then coalesce(cast(response_int as text), response_text) end) as "Being who I am today is a privilege I enjoy which thereby makes me want to contribute to society",
        max(case when question_code = 'question_150' then coalesce(cast(response_int as text), response_text) end) as "I know various possible ways by which I can help those in need",
        max(case when question_code = 'question_151' then coalesce(cast(response_int as text), response_text) end) as "The compassion I feel when I see people living in extreme poverty, strongly motivates me to act for social change",
        max(case when question_code = 'question_152' then coalesce(cast(response_int as text), response_text) end) as "I apply 'value-based criteria' while making important life decisions",
        max(case when question_code = 'question_153' then coalesce(cast(response_int as text), response_text) end) as "The righteous anger I feel when I see injustice in the society, strongly motivates me to act for social change",
        max(case when question_code = 'question_154' then coalesce(cast(response_int as text), response_text) end) as "I understand the importance & unique roles of a vibrant social sector in addition to the government & private sectors",
        max(case when question_code = 'question_155' then coalesce(cast(response_int as text), response_text) end) as "I take a firm stand on my values even when others around me are behaving differently",
        max(case when question_code = 'question_156' then coalesce(cast(response_int as text), response_text) end) as "Who I am today is determined more by the chance elements of life than my own efforts",
        max(case when question_code = 'question_157' then coalesce(cast(response_int as text), response_text) end) as "Since I have received a lot from society, I want to give back through social contribution",
        max(case when question_code = 'question_158' then coalesce(cast(response_int as text), response_text) end) as "I take important life decisions by applying test of values / morals",
        max(case when question_code = 'question_159' then coalesce(cast(response_int as text), response_text) end) as "I am confident of earning sufficient money in future",
        max(case when question_code = 'question_160' then coalesce(cast(response_int as text), response_text) end) as "I can visualize myself pursuing a career in the social sector",
        max(case when question_code = 'question_161' then coalesce(cast(response_int as text), response_text) end) as "Agreement with parents is a mandatory condition for me for making important life decisions",
        max(case when question_code = 'question_162' then coalesce(cast(response_int as text), response_text) end) as "Living in harmony with nature is an important part in my life",
        max(case when question_code = 'question_163' then coalesce(cast(response_int as text), response_text) end) as "I feel inspired to bring about social impact",
        max(case when question_code = 'question_164' then coalesce(cast(response_int as text), response_text) end) as "I feel excited with the prospect of discovering / pursuing my life purpose",
        max(case when question_code = 'question_165' then coalesce(cast(response_int as text), response_text) end) as "I am committed to be part of a social change movement",
        max(case when question_code = 'question_166' then coalesce(cast(response_int as text), response_text) end) as "I believe my purpose is to make a meaningful difference in the society",
        max(case when question_code = 'question_167' then coalesce(cast(response_int as text), response_text) end) as "I am committed to be part of a youth community working for social change",
        max(case when question_code = 'question_168' then coalesce(cast(response_int as text), response_text) end) as "In the existing representative democracy, I can enact my responsibilities as an 'Active Citizen'",
        max(case when question_code = 'question_169' then coalesce(cast(response_int as text), response_text) end) as "The safety and security needs of life occupy a major part of my thoughts and mental world",
        -- Batch 17 questions (q170-q178)
        max(case when question_code = 'question_170' then coalesce(cast(response_int as text), response_text) end) as "My approach to leading life is to complete a bucket list to maximise my happiness",
        max(case when question_code = 'question_171' then coalesce(cast(response_int as text), response_text) end) as "I usually spend my every day intentionally, engaging in activities linked to my long-term purpose",
        max(case when question_code = 'question_172' then coalesce(cast(response_int as text), response_text) end) as "I feel an urgency to act on the issue of climate change",
        max(case when question_code = 'question_173' then coalesce(cast(response_int as text), response_text) end) as "While contemplating about social change, I often feel lonely",
        max(case when question_code = 'question_174' then coalesce(cast(response_int as text), response_text) end) as "Income inequality in the world is justified as talented people are bound to earn more",
        max(case when question_code = 'question_175' then coalesce(cast(response_int as text), response_text) end) as "I am proactively taking steps to become an independent & responsible adult",
        max(case when question_code = 'question_176' then coalesce(cast(response_int as text), response_text) end) as "I carefully consider my needs before making any purchases",
        max(case when question_code = 'question_177' then coalesce(cast(response_int as text), response_text) end) as "I realize the importance of having mentors (non-family elders) whom I can ask for continued growth input.",
        max(case when question_code = 'question_178' then coalesce(cast(response_int as text), response_text) end) as "I am actively cultivating relationship with mentor(s)",
        -- Finance questions (5)
        max(case when question_code = 'finance_1' then coalesce(cast(response_int as text), response_text) end) as "Monthly income at age 25",
        max(case when question_code = 'finance_2' then coalesce(cast(response_int as text), response_text) end) as "Monthly income at age 30",
        max(case when question_code = 'finance_3' then coalesce(cast(response_int as text), response_text) end) as "Monthly income as per Financial sheet",
        max(case when question_code = 'finance_4' then coalesce(cast(response_int as text), response_text) end) as "Monthly income Divided by 2",
        max(case when question_code = 'finance_5' then coalesce(cast(response_int as text), response_text) end) as "Financially independent in next N years"

    from {{ ref('int_nirman_questionnaire') }}
    group by participant_id, participant_name, workshop_name, batch, workshop_phase
)

select * from base_data